#######################################################################
#                          General settings                           #
#######################################################################

# The following settings are read by Optima++ and will be applied
# to each simulation corresponding to this settings tag

# absolute tolerance
# optional
# default 1e-15
absoluteTolerance: 1e-15

# Relative tolerance
# optional
# default 1e-9
relativeTolerance: 1e-12


reactorType: isothermal

